### PR TITLE
Enable validation of OSI trace file and LFS storage traces

### PR DESCRIPTION
**Pull request by vkresch**
#### Reference to a related issue in the repository
No related issue just improvement of the storage and extension of validation of OSI trace files.

#### Add a description
**What is this change?**
This PR adds the functionality to the validator to validate OSI messages in the new format type (length of osi message and osi message). The trace files willl now be store through git lfs.

**Changnotes**
- Saving lzma compressed trace files in git lfs
- Enabling validation with new OSI format and in lzma compressed format
- Update README (now shorter and concise)
- Added more validation cases to the travis CI
- Updated setup.py with copy location of the requirements to the correct path, change python version to 3.6 and the version of the validator to 0.5
- Updated documentation how to validate compressed and non-compressed trace files
- corrected import paths to more explicit naming

 **Does it break any existing functionality or force me to update to a new version?**
It is now optional to validate the old `$$__$$` separated trace files. Furthermore there exists the optional possibility to validate lzma compressed OSI trace files directly. 

**How has it been tested?**
It has been tested with the two compressed trace file in the data directory. For more see the [travis ci output](https://travis-ci.org/OpenSimulationInterface/osi-validation/builds/614463608?utm_source=github_status&utm_medium=notification).

#### Mention a member
@jdsika let me know you thoughts, suggestions and improvements ;)

#### Check the checklist

- [x] My code and comments follow the [contributors guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/howtocontribute.html) of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the [documentation](https://github.com/OpenSimulationInterface/osi-documentation) for osi-validation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests / travis ci pass locally with my changes.

### CODE REVIEW

**Comment by pmai** [comment]
While we are at it, should not osivalidator use open-simulation-interface as a submodule, like the other repos (OSMP, osi-viewer, ...) do, to ensure that the validator and the OSI version by default match? Not something to put into this PR, it just occurred to me during reviewing the changes (superficially).

**Comment by jdsika** [comment]
I had the same exact thought and wanted to discuss this with you today @vkresch

**Comment by vkresch** [comment]
@jdsika send me an email invitation. I have time from 4pm.

**Comment by jdsika** [comment]
Please have a look at subtrees instead of submodules [here](https://www.atlassian.com/git/tutorials/git-subtree)

**Comment by pmai** [comment]
Given the tradeoffs involved we should stick to submodules for the inter-module dependencies of OSI.

**Pull request merged**
